[keyboard]
type = "keyboard"

cancel = "esc"
select = "enter"

up = ["up", "repeat"]
down = ["down", "repeat"]
right = ["right", "repeat"]
left = ["left", "repeat"]
rotate_right = "x"
rotate_left = "z"
soft_fall = "lshift"
hard_fall = "space"
hold = "c"


[snes]
type = "joystick"

cancel = 8
select = 9

up = ["axis", "1", "-", "repeat"]
down = ["axis", "1", "+", "repeat"]
right = ["axis", "0", "+", "repeat"]
left = ["axis", "0", "-", "repeat"]
rotate_right = 5
rotate_left = 4
soft_fall = 1
hard_fall = 2
hold = 3
